#!/bin/bash
# vim:tw=0:ts=4:sw=4:et:norl:nospell:

# This INIT INFO block is required, per
#   http://wiki.debian.org/LSBInitScripts

# See also:
#  http://blog.scphillips.com/posts/2013/07/getting-a-python-script-to-run-in-the-background-as-a-service-on-boot/

### BEGIN INIT INFO
# Provides:          beerme-always-and-forever
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Raugupatis beer daemon
# Description:       Raugupatis beer daemon
### END INIT INFO

# To install (on yer Pi):
INSTALL_CXPX_="
cd /home/pi
git clone http://github.com/landonb/raugupatis
cd raugupatis/pi-beer
sudo /bin/cp beerme-always-and-forever /etc/init.d/
sudo /bin/chmod 755 /etc/init.d/beerme-always-and-forever
sudo /bin/chown root /etc/init.d/beerme-always-and-forever
sudo /bin/chgrp root /etc/init.d/beerme-always-and-forever
sudo update-rc.d beerme-always-and-forever defaults
# And then add the URL and token to the init.d script:
sudo nano /etc/init.d/beerme-always-and-forever
"
# IMPORTANT: Add your credentials here:
SPHINX_URL="https://localhost"

DIR=/home/pi/raugupatis/pi-beer
DAEMON=$DIR/beerme.py
DAEMON_NAME=beerme.py

DAEMON_OPTS="--host \"${SPHINX_URL}\""

DAEMON_USER=pi

PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON -- $DAEMON_OPTS
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0

